[package]
name = "reverse-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
hyper = "1.2.0"
hyper-util = { version = "0.1.3", features = ["client-legacy"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
